# Generated by Django 3.2.7 on 2021-09-09 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0005_alter_project_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='card',
            name='parent_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='tracker_app.list'),
        ),
        migrations.AlterField(
            model_name='list',
            name='parent_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='tracker_app.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=200)),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yourcomments', to=settings.AUTH_USER_MODEL)),
                ('parent_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tracker_app.card')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
