# Generated by Django 3.2.7 on 2021-09-30 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0007_alter_project_project_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='assignes',
            new_name='assignees',
        ),
    ]
