# Generated by Django 3.2.7 on 2021-10-08 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0008_rename_assignes_card_assignees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='assignees',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
