# Generated by Django 3.2.7 on 2021-09-09 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0004_auto_20210908_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
